.PHONY: backend-install backend-dev db-upgrade db-migrate test-backend frontend-install frontend-dev frontend-build

# --- Backend ---

backend-install:
	cd backend && python3 -m venv .venv && .venv/bin/pip install -r requirements.txt

backend-dev:
	cd backend && .venv/bin/uvicorn app.main:app --reload --port 8000

# Apply all pending migrations.
db-upgrade:
	cd backend && .venv/bin/alembic upgrade head

# Create a new autogenerated migration: make db-migrate m="add xyz"
db-migrate:
	cd backend && .venv/bin/alembic revision --autogenerate -m "$(m)"

test-backend:
	cd backend && .venv/bin/python -m pytest

# --- Frontend ---

frontend-install:
	cd frontend && npm install

frontend-dev:
	cd frontend && npm run dev

frontend-build:
	cd frontend && npm run build
