"""initial schema

Revision ID: 3803a27ee240
Revises: 
Create Date: 2026-10-06 14:45:30.565418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3803a27ee240'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'remote', name='repositorysource', native_enum=False, length=32), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ingesting', 'ready', 'error', name='repositorystatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('author_count', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_owner_id'), ['owner_id'], unique=False)

    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('primary_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_authors_repository_id'), ['repository_id'], unique=False)

    op.create_table('mailmap_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=True),
    sa.Column('canonical_email', sa.String(length=320), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'source_name', 'source_email', name='uq_mailmap_entry')
    )
    with op.batch_alter_table('mailmap_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailmap_entries_repository_id'), ['repository_id'], unique=False)

    op.create_table('author_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('source', sa.Enum('auto', 'mailmap', 'manual', name='identitysource', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'email', 'name', name='uq_author_identity_repo_email_name')
    )
    with op.batch_alter_table('author_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_identities_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_author_identities_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_author_identities_repository_id'), ['repository_id'], unique=False)

    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_identity_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_email', sa.String(length=320), nullable=True),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committer_name', sa.String(length=255), nullable=True),
    sa.Column('committer_email', sa.String(length=320), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('parent_shas', sa.JSON(), nullable=True),
    sa.Column('is_merge', sa.Boolean(), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_identity_id'], ['author_identities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'sha', name='uq_commit_repo_sha')
    )
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commits_author_id'), ['author_id'], unique=False)
        batch_op.create_index('ix_commits_repo_authored_at', ['repository_id', 'authored_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commits_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commits_sha'), ['sha'], unique=False)

    op.create_table('commit_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('old_path', sa.String(length=1024), nullable=True),
    sa.Column('change_type', sa.String(length=1), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('is_binary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commit_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commit_files_commit_id'), ['commit_id'], unique=False)
        batch_op.create_index('ix_commit_files_repo_path', ['repository_id', 'path'], unique=False)
        batch_op.create_index(batch_op.f('ix_commit_files_repository_id'), ['repository_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commit_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commit_files_repository_id'))
        batch_op.drop_index('ix_commit_files_repo_path')
        batch_op.drop_index(batch_op.f('ix_commit_files_commit_id'))

    op.drop_table('commit_files')
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commits_sha'))
        batch_op.drop_index(batch_op.f('ix_commits_repository_id'))
        batch_op.drop_index('ix_commits_repo_authored_at')
        batch_op.drop_index(batch_op.f('ix_commits_author_id'))

    op.drop_table('commits')
    with op.batch_alter_table('author_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_identities_repository_id'))
        batch_op.drop_index(batch_op.f('ix_author_identities_email'))
        batch_op.drop_index(batch_op.f('ix_author_identities_author_id'))

    op.drop_table('author_identities')
    with op.batch_alter_table('mailmap_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mailmap_entries_repository_id'))

    op.drop_table('mailmap_entries')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_repository_id'))
        batch_op.drop_index(batch_op.f('ix_authors_display_name'))

    op.drop_table('authors')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_owner_id'))
        batch_op.drop_index(batch_op.f('ix_repositories_name'))

    op.drop_table('repositories')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
